[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
universe_solana_backend = "2gfJsBnr74xVFPhgxJFAfZLvy8y3FnUDppcRoEGsQ3dm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/macsap/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"